### ISSUE TITLE
JSON:API libs & farmOS 2.x migration

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS.js#19]
Just want to start an issue for discussing the eventual migration to farmOS 2.x and what that will entail, especially WRT JSON:API.

**Comment by jgaehring** [comment]
One promising library:

https://github.com/reststate/reststate-client

**Comment by jgaehring** [comment]
The official list of implementations: 

https://jsonapi.org/implementations/

**Comment by mstenta** [comment]
FYI I have started documenting "farmOS API Changes from 1.x to 2.x" in my `api2x` branch here (work in progress): https://github.com/mstenta/farmOS/blob/api2x/docs/api/changes.md

My hope is that these docs will serve as a guide for 2.x compatibility in farmOS.js, farmOS.py, Field Kit, and others.

**Comment by jgaehring** [comment]
This issue is a little too general at this point, so closing.
