### ISSUE TITLE
Any method except Authorization and Farm Info returns 403 Forbidden

### ISSUE THREAD

**Issue by MohamedFarid2018** [farmOS/farmOS.js#29]

**Comment by jgaehring** [comment]
Can you provide any more details regarding the server you're attempting to connect to, whether you're doing so in Node or the browser, and which version of farmOS.js this relates to?

And just to make clear, this library is still considered experimental, as the warning in the README indicates. It won't be considered stable until we complete the conversion for farmOS 2.0, which is underway but still has a ways to go.

**Comment by MohamedFarid2018** [comment]
sorry, it was my mistake. I should set the scope as "user_access" not "farm_info"
