### ISSUE TITLE
incorrect area_type key in js object

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS.js#3]
I believe the object returned from the server labels this as "area_type" not "field_farm_area_type" But I may be mistaken, this could be a difference between languages or my misinterpretation farmOS.js?

Just an issue I came across while cross-referencing APIs.

https://github.com/farmOS/farmOS.js/blame/master/README.md#L230

**Comment by jgaehring** [comment]
Good catch, thanks @paul121!
