### ISSUE TITLE
Merge dependabot PR's

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS.js#36]
I keep forgetting to merge #28 and #32. Since I've already tagged 3 alphas at this point, I don't want to rebase on these PR's, and therefore I don't think these will make it into the old 1.x library. That's another good reason to deprecate that library at this point. And this might be a separate issue, but it could be a good time to set the `main` branch at the most recent alpha commit as well, to prevent confusion on the status of this library as a whole, as in https://github.com/farmOS/farmOS.js/issues/29#issuecomment-853277956 and other more recent issues.

**Comment by jgaehring** [comment]
Actually, I might just go ahead and do all this now, including a reset of the `main` branch onto the the `2.0.0-alpha.3` tag. @mstenta, any objections?

**Comment by mstenta** [comment]
I think that makes sense! No objections.

**Comment by jgaehring** [comment]
Resolve by 3f0a27a.
